apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryplan-proxy
spec:
  selector:
    matchLabels:
      app: queryplan-proxy
  template:
    metadata:
      labels:
        app: queryplan-proxy
    spec:
      containers:
        - name: queryplan-proxy
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
          image: queryplan-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - name: queryplan-proxy
              containerPort: 3306
          envFrom:
            - secretRef:
                name: queryplan-proxy
