apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryplan-proxy
spec:
  selector:
    matchLabels:
      app: queryplan-proxy
  template:
    metadata:
      labels:
        app: queryplan-proxy
    spec:
      containers:
        - name: queryplan-proxy
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: queryplan-proxy
              containerPort: {{ .Values.connection.bindPort }}
          envFrom:
            - secretRef:
                name: queryplan-proxy
          {{- if .Values.connection.useSecret }}
          env:
            - name: QUERYPLAN_LIVE_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connection.secretName }}
                  key: {{ .Values.connection.secretKey }}
          {{- end }}
