apiVersion: v1
kind: Secret
metadata:
  name: queryplan-proxy
type: Opaque
stringData:
  {{- if not .Values.connection.useSecret }}
  QUERYPLAN_LIVE_CONNECTION_URI: {{ required "Error: liveUri is required" .Values.connection.liveUri | printf "%s" }}
  {{- end }}
  QUERYPLAN_DATABASE_NAME: {{ required "Error: databaseName is required" .Values.connection.databaseName | printf "%s" }}
  QUERYPLAN_DBMS: {{ required "Error: engine is required" .Values.engine | printf "%s" }}
  QUERYPLAN_BIND_ADDRESS: {{ required "Error: bindAddress is required" .Values.connection.bindAddress | printf "%s" }}
  QUERYPLAN_BIND_PORT: {{ required "Error: bindPort is required" .Values.connection.bindPort | printf "%v" }}
  QUERYPLAN_UPSTREAM_ADDRESS: {{ required "Error: upstreamAddress is required" .Values.connection.upstreamAddress | printf "%s" }}
  QUERYPLAN_UPSTREAM_PORT: {{ required "Error: upstreamPort is required" .Values.connection.upstreamPort | printf "%v" }}
  QUERYPLAN_API_URL: {{ required "Error: apiUrl is required" .Values.apiUrl | printf "%s" }}
  QUERYPLAN_TOKEN: {{ required "Error: token is required" .Values.connection.token | printf "%s" }}
  QUERYPLAN_ENV: {{ required "Error: environment is required" .Values.environment | printf "%s" }}
