apiVersion: v1
kind: Secret
metadata:
  name: queryplan-proxy
type: Opaque
data:
  {{- if not .Values.connection.useSecret }}
  QUERYPLAN_LIVE_CONNECTION_URI: {{ required "Error: liveUri is required" .Values.connection.liveUri | quote | b64enc }}
  {{- end }}
  QUERYPLAN_DATABASE_NAME: {{ required "Error: databaseName is required" .Values.connection.databaseName | quote | b64enc }}
  QUERYPLAN_DBMS: {{ required "Error: engine is required" .Values.engine | quote | b64enc }}
  QUERYPLAN_BIND_ADDRESS: {{ required "Error: bindAddress is required" .Values.connection.bindAddress | quote | b64enc }}
  QUERYPLAN_BIND_PORT: {{ required "Error: bindPort is required" .Values.connection.bindPort | quote | b64enc }}
  QUERYPLAN_UPSTREAM_ADDRESS: {{ required "Error: upstreamAddress is required" .Values.connection.upstreamAddress | quote | b64enc }}
  QUERYPLAN_UPSTREAM_PORT: {{ required "Error: upstreamPort is required" .Values.connection.upstreamPort | quote| b64enc }}
  QUERYPLAN_API_URL: {{ required "Error: apiUrl is required" .Values.apiUrl | quote | b64enc }}
  QUERYPLAN_TOKEN: {{ required "Error: token is required" .Values.connection.token | quote| b64enc }}
  QUERYPLAN_ENV: {{ required "Error: environment is required" .Values.environment | quote | b64enc }}
