apiVersion: v1
kind: Service
metadata:
  name: queryplan-proxy
spec:
  selector:
    app: queryplan-proxy
  ports:
    - name: queryplan-proxy
      port: {{ .Values.connection.bindPort }}
      targetPort: {{ .Values.connection.bindPort }}
