apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryplan-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryplan-proxy
  template:
    metadata:
      labels:
        app: queryplan-proxy
    spec:
      containers:
      - name: queryplan-proxy
        image: queryplan-proxy
        ports:
        - containerPort: 3000
